In [1]:
pip install numpy scipy matplotlib pandas ipykernel

Requirement already satisfied: numpy in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.3)
Collecting scipy
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: pandas in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: ipykernel in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.2.0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: comm>=0.1.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (9.12.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.4)
Requirement already satisfied: six>=1.5 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   -- ------------------------------------- 2.1/37.3 MB 10.0 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/37.3 MB 10.9 MB/s eta 0:00:04
   ------- -------------------------------- 6.6/37.3 MB 10.2 MB/s eta 0:00:04
   ---------- ----------------------------- 10.2/37.3 MB 12.1 MB/s eta 0:00:03
   -------------- ------------------------- 13.9/37.3 MB 13.4 MB/s eta 0:00:02
   ------------------- -------------------- 17.8/37.3 MB 14.2 MB/s eta 0:00:02
   ------------------------ --------------- 22.5/37.3 MB 15.3 MB/s eta 0:00:01
   ---------------------------- ----------- 26.5/37.3 MB 15.9 MB/s eta 0:00:01
   -------------------------------- ------- 30.7/37.3 MB 16.4 MB/s eta 0:00:01
   ------------------------------------- -- 34.9/37.3 MB 16.9 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 16.4 MB/s  0:00:02
Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   -------------------- ------------------- 5.0/9.5 MB 23.0 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 21.2 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 19.9 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 20.4 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   --------------------- ------------------ 3.9/7.2 MB 20.2 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 18.0 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: scipy, pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ---------------------------------------- 0/8 [scipy]
   ----- ---------------------------------- 1/8 [pyparsing]
   ---------- ----------------------------- 2/8 [pillow]
   ---------- ----------------------------- 2/8 [pillow]
   ---------- ----------------------------- 2/8 [pillow]
   ---------- ----------------------------- 2/8 [pillow]
   ---------- ----------------------------- 2/8 [pillow]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   -------------------- ------------------- 4/8 [fonttools]
   ------------------------------ --------- 6/8 [contourpy]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ----------------------------------- ---- 7/8 [matplotlib]
   ---------------------------------------- 8/8 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.1 pillow-12.3.0 pyparsing-3.3.2 scipy-1.18.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install yfinance numpy

Collecting yfinance
  Downloading yfinance-1.6.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: numpy in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.14.3)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.0-cp310-abi3-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: lxml>=4.9.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (6.0.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (3.0.1)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.9.4)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests>=2.31 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.32.5)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.0.1-cp314-cp314-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.2.25)
Requirement already satisfied: pycparser in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\chino\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Downloading yfinance-1.6.0-py3-none-any.whl (148 kB)
Downloading curl_cffi-0.16.0-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 10.9 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.3.0-py3-none-any.whl (179 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Downloading websockets-17.0.1-cp314-cp314-win_amd64.whl (212 kB)
Installing collected packages: pytz, multitasking, websockets, protobuf, peewee, curl_cffi, yfinance

   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------------- ---------------------- 3/7 [protobuf]
   ---------------------- ----------------- 4/7 [peewee]
   ---------------------- ----------------- 4/7 [peewee]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------------- 7/7 [yfinance]

Successfully installed curl_cffi-0.16.0 multitasking-0.0.13 peewee-4.3.0 protobuf-7.35.1 pytz-2026.3.post1 websockets-17.0.1 yfinance-1.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import norm

print(np.__version__, pd.__version__, yf.__version__)

2.4.3 3.0.1 1.6.0

In [2]:
data = yf.download("AAPL", start="2025-01-01", end="2026-01-01", auto_adjust=True)
print(data.shape)
data.head()

[*********************100%***********************]  1 of 1 completed

(250, 5)

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-01-02  242.093124  247.305299  240.077751  247.136511  55740700
2025-01-03  241.606659  242.420743  240.147249  241.606659  40244100
2025-01-06  243.234848  245.548063  241.447813  242.549817  45045600
2025-01-07  240.464966  243.780899  239.611161  241.229407  40856000
2025-01-08  240.951401  241.954134  238.320499  240.177022  37628900

In [7]:
import numpy as np
import pandas as pd

np.random.seed(32)

In [8]:
tamaños = [10, 100, 1000, 10000, 100000]
E_teorica = 3.5

n_sims = []
esperanzas = []
errores = []

for i in tamaños:
    tiradas = np.random.randint(1, 7, size=i)
    media = tiradas.mean()

    n_sims.append(i)
    esperanzas.append(media)
    errores.append(abs(media - E_teorica))

In [9]:
tabla = pd.DataFrame({
    'N': n_sims,
    'Esperanza simulada': esperanzas,
    'Esperanza teórica': E_teorica,
    'Error absoluto': errores
})

tabla

        N  Esperanza simulada  Esperanza teórica  Error absoluto
0      10             4.00000                3.5         0.50000
1     100             3.32000                3.5         0.18000
2    1000             3.40300                3.5         0.09700
3   10000             3.48860                3.5         0.01140
4  100000             3.50205                3.5         0.00205

### Caso Hipotetico
Tirar 3 dados consecutivamente, y quiero apostar 10,000 pesos a que cada tiro sale un numero mayor que el anterior, cual es la probabilidad de que gane la apuesta? usando Montecarlo

In [10]:
np.random.seed(32)

N = 100000
victorias = 0

for i in range(N):
    d1 = np.random.randint(1, 7)
    d2 = np.random.randint(1, 7)
    d3 = np.random.randint(1, 7)
    if d1 < d2 < d3:
        victorias += 1

prob = victorias / N
print(f"P(ganar) = {prob}")

P(ganar) = 0.0925